import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Card from '../components/Card'

const Home: NextPage = () => {
  const router = useRouter()
  const navigate = (x: string) => router.push(x)
  const apiRoute = async () => {
    const response = await fetch('/api/apiRoute', {
      method: 'GET',
    })
    const result = await response.json()
    alert(result.data)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.btn} onClick={() => navigate('/useEffect')}>
        <Card>useEffect</Card>
      </div>
      <div className={styles.btn} onClick={() => navigate('/staticProps')}>
        <Card>staticProps</Card>
      </div>
      <div className={styles.btn} onClick={() => navigate('/serverSideProps')}>
        <Card>serverSideProps</Card>
      </div>
      <div className={styles.btn} onClick={() => navigate('/staticPath')}>
        <Card>staticPath</Card>
      </div>
      <div className={styles.btn} onClick={() => apiRoute()}>
        <Card>apiRoute</Card>
      </div>
      <div className={styles.btn} onClick={() => navigate('/imageOpt')}>
        <Card>imageOpt</Card>
      </div>
    </div>
  )
}

export default Home
