import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Css.module.scss'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/nested">
        <div className={styles.card}>Next.js!</div>
      </Link>
    </div>
  )
}

export default Home
